name : package-getting-started-app
on : [push]
jobs :
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
    # - checkout le code 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test after checkout
        run: ls
    # - build et tag image
      - name: Build and tag image
        run: |
          docker build -t xlslade/package-getting-started-app:${{ github.sha }} .
    # - push sur dockerhub  
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: docker push xlslade/package-getting-started-app:${{ github.sha }}



