name : package-getting-started-app
on : [push]
jobs :
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
    # - checkout le code 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test after checkout
        run: ls
     # - build l'image     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     # - login et push dockerhub 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: xlslade/package-getting-started-app:${{ github.sha }}



